sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rowin1125/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rowin1125/docker-react npm run test
